//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcrParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Stations = new HashSet<Station>();
        }
    
        public long Id { get; set; }
        public string ThumbUrl { get; set; }
        public string FullImageUrl { get; set; }
    
        public virtual ICollection<Station> Stations { get; set; }
    }
}
