//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcrParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int Id { get; set; }
        public long Ecr { get; set; }
        public long ExpressCode { get; set; }
        public string StationName { get; set; }
        public int PositionId { get; set; }
        public Nullable<long> OpenStreetMapNode { get; set; }
        public string OpenStreetMapUrl { get; set; }
        public int StationTypeId { get; set; }
        public Nullable<long> ImageId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Position Position { get; set; }
        public virtual StationType StationType { get; set; }
    }
}
